In [2]:
import numpy as np

**Task 1**

In [3]:
x = np.array([2, 3])
y = np.array([1])
w = np.array([0.4, 3])
b = np.array([-9])
eta = 0.1
lmbda = 0.1

In [4]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

In [5]:
def feedforward(x, y, w, b):
    z = x.T @ w + b
    return z

In [6]:
def calcCrossEntropyFunctionR(w, y, a, lmbda):
    q = w.shape[0]
    reg_term = np.sum(abs(w)) * (lmbda)
    return -1.0 * (y * np.log(a) + (1 - y) * np.log(1 - a)) + reg_term

In [7]:
def backprop(w, b, x, y, a, eta, lmbda):
    delta = a - y
    dC_dw_1 = delta * x[0]
    dC_dw_2 = delta * x[1]
    dC_db = delta

    w_1 = w[0] - (eta * lmbda) * signum(w[0]) - eta * dC_dw_1
    w_2 = w[1] - (eta * lmbda) * signum(w[1]) - eta * dC_dw_2
    b_1 = b[0] - eta * dC_db

    return np.array([w_1, w_2]), np.array([b_1])

In [8]:
def signum(x):
    if x == 0:
        return 0 
    elif x > 0:
        return 1 
    else:
        return -1 

In [9]:
feedforward(x, y, w, b) # correct

array([0.8])

In [10]:
a = sigmoid(feedforward(x, y, w, b)) # correct
a

array([0.68997448])

In [11]:
new_w, new_b = backprop(w, b, x, y, a, eta, lmbda)
result = sigmoid(feedforward(x, y, new_w, new_b))
result

array([[0.76567266]])

**Task 2**

In [12]:
n = 631
v = 1.0 / n
v

0.001584786053882726

**Task 3**

In [13]:
# def softmax():

In [14]:
x = np.array([1, 0, 0, 1])
y = np.array([0.1, 0.1, np.nan])

0.1 = e ^ (z_j) / 

In [15]:
z = feedforward(x, y, w, b)

# 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

Сумма активаций Softmax для каждого выходного нейрона сети равна 1.
Исходя из этого свойства, можно определить, что искомое значение активации нейрона равно разности единицы (1) и суммы известных значений активаций нейронов.

Если первые два значения активации нейронов равны 0.1, то третье значение равно
1 - (0.1 + 0.1) = 0.8