In [117]:
import numpy as np

In [118]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [119]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356])

In [120]:
np.exp(arr)

array([1.        , 2.71828183, 7.3890561 ])

In [121]:
x = np.random.randn(3)
y = np.random.randn(3)

In [122]:
x

array([-1.43047504, -0.29502344,  0.8916887 ])

In [123]:
y

array([ 0.49274171,  0.541262  , -0.01569216])

In [124]:
np.maximum(x, y)

array([0.49274171, 0.541262  , 0.8916887 ])

In [125]:
x

array([-1.43047504, -0.29502344,  0.8916887 ])

In [126]:
remainder, whole_part = np.modf(x)
remainder

array([-0.43047504, -0.29502344,  0.8916887 ])

In [127]:
whole_part

array([-1., -0.,  0.])

In [128]:
arr = np.random.randn(3)
arr

array([ 1.09215843, -0.13316817, -0.20548959])

In [129]:
np.sqrt(arr, arr)

/tmp/ipykernel_15283/269955669.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([1.04506384,        nan,        nan])

In [130]:
arr

array([1.04506384,        nan,        nan])

Унарные u-функции: abs, fabs; sqrt; square; exp; log, log10, log2, log1p; sign; ceil; floor; rint; modf; isnan; isfinite, isinf; cos,
cosh, sin, sinh, tan, tanh; arccos, arccosh, arcsin, arcsinh, arctan, arctanh; logical_not
Бинарные u-функции: add; subtract; multiply; divide, floor_divide; power; maximum, fmax; minimum, fmin; mod; copysing;
greater, greater_equal, less, less_equal, equal, not_equal; logical_and; logical_or; logical_xor.

**Задание 1:**

1. Привидите практические примеры всех унарных функций, перечисленных выше. В отдельной строке перед примером
необходимо дать описание каждой функции.
2. Привидите практические примеры всех бинарных функций, перечисленных выше. В отдельной строке перед
примером необходимо дать описание каждой функции.

abs: Возвращает абсолютное значение элемента.

In [131]:
arr = np.array([-1, -2, -3])
result = np.abs(arr)
result

array([1, 2, 3])

fabs: Возвращает абсолютное значение как число с плавающей запятой.

In [132]:
arr = np.array([-1.5, -2.2, -3.3233])
result = np.fabs(arr)
result

array([1.5   , 2.2   , 3.3233])

In [133]:
# sqrt: возвращает кв. корень элемента
arr = np.array([4, 9, 100])
result = np.sqrt(arr)
result

array([ 2.,  3., 10.])

In [134]:
# square: возвращает квадрат элемента
arr = np.array([1, 2, 3])
result = np.square(arr)
result

array([1, 4, 9])

In [135]:
# exp: возвращает число e, возведённое в степень элемента
arr = np.array([1, 2, 3])
result = np.exp(arr)
result


array([ 2.71828183,  7.3890561 , 20.08553692])

In [136]:
# log: возвращает натуральный логарифм элемента
arr = np.array([1, np.e, np.e ** 2])
result = np.log(arr)
result

array([0., 1., 2.])

In [137]:
# log10: возвращает десятичный логарифм
arr = np.array([1, 10, 100])
result = np.log10(arr)
result

array([0., 1., 2.])

In [138]:
arr = np.array([2, 32, 128])
result = np.log2(arr) # возвращает двоичный логарифм элемента
result

array([1., 5., 7.])

In [139]:
arr = np.array([0.0, np.e - 1, np.e ** 2 - 1])
result = np.log1p(arr) # возвращает натуральный логарифм (1+х) для элемента
result

array([0., 1., 2.])

In [140]:
arr = np.array([-1, 10, 0])
result = np.sign(arr) # возвращает знак элемента (-1 - элемент отриц, 0 - 0, 1 - эл. полож)
result

array([-1,  1,  0])

In [141]:
arr = np.array([-1.5, -2.2, -3.3233])
result = np.ceil(arr) # ceil: возвращает наименьшее число, большее или равное элементу
result

array([-1., -2., -3.])

In [142]:
arr = np.array([-1.5, -2.2, -3.3233])
result = np.floor(arr) # floor: возвращает наибольшее число, меньшее или равное элементу
result

array([-2., -3., -4.])

In [143]:
arr = np.array([-1.5, -2.2, -3.3233])
result = np.rint(arr) # rint: округляет до ближайшего целого числа
result

array([-2., -2., -3.])

In [144]:
arr = np.array([-1.5, -2.2, np.nan])
result = np.isnan(arr) # isnan: проверка на наличие NaN
result

array([False, False,  True])

In [145]:
arr = np.array([-1.5, np.inf, np.nan])
result = np.isfinite(arr) # isfinite: проверка элементов на их конечность
result

array([ True, False, False])

In [146]:
arr = np.array([-1.5, np.inf, np.nan])
result = np.isinf(arr) # isinf: проверка элементов на их конечность
result

array([False,  True, False])

In [147]:
arr = np.array([0, np.pi/2, np.pi])
result = np.cos(arr) # cos: вычисляет косинус элемента
result

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [148]:
arr = np.array([0, np.pi/2, np.pi])
result = np.cosh(arr) # cosh: вычисляет гиперболический косинус
result

array([ 1.        ,  2.50917848, 11.59195328])

In [149]:
arr = np.array([0, np.pi/2, np.pi])
result = np.sin(arr) # sin: вычисляет синус 
result_h = np.sinh(arr) # sinh: вычиляет гиперболический синус
print(result)
print(result_h)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 0.          2.3012989  11.54873936]


In [150]:
arr = np.array([0, np.pi/2, np.pi])
result = np.tan(arr) # tan: вычисляет тангенс 
result_h = np.tanh(arr) # tanh: вычиляет гиперболический тангенс
print(result)
print(result_h)

[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[0.         0.91715234 0.99627208]


In [151]:
arr = np.array([0, np.pi/2, np.pi])
result = np.arccos(arr) # arccos: вычисляет арккосинус 
result_h = np.arccosh(arr) # arccosh: вычиляет гиперболический арккосинус
print(result)
print(result_h)

[1.57079633        nan        nan]
[       nan 1.02322748 1.81152627]


/tmp/ipykernel_15283/3779833803.py:2: RuntimeWarning: invalid value encountered in arccos
  result = np.arccos(arr) # arccos: вычисляет арккосинус
/tmp/ipykernel_15283/3779833803.py:3: RuntimeWarning: invalid value encountered in arccosh
  result_h = np.arccosh(arr) # arccosh: вычиляет гиперболический арккосинус


In [152]:
arr = np.array([0, np.pi/2, np.pi])
result = np.arcsin(arr) # arcsin: вычисляет арксинус
result_h = np.arcsinh(arr) # arcsinh: вычиляет гиперболический арксинус
print(result)
print(result_h)

[ 0. nan nan]
[0.         1.23340312 1.86229574]


/tmp/ipykernel_15283/283820762.py:2: RuntimeWarning: invalid value encountered in arcsin
  result = np.arcsin(arr) # arcsin: вычисляет арксинус


In [153]:
arr = np.array([True, False, True, False])
result = np.logical_not(arr) # logical_not: меняет булевы значения наоборот
result

array([False,  True, False,  True])

**Бинарные функции:**

In [154]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.add(arr1, arr2) # суммирует элементы массивов
result

array([5, 7, 9])

In [155]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.subtract(arr1, arr2) # вычитает элементы массивов
result

array([-3, -3, -3])

In [156]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.multiply(arr1, arr2) # перемножает элементы массивов
result

array([ 4, 10, 18])

In [157]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.divide(arr1, arr2) # находит частное элементов массивов
result

array([0.25, 0.4 , 0.5 ])

In [158]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.floor_divide(arr1, arr2) # находит целочисленное частное элементов массивов
result

array([0, 0, 0])

In [159]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.power(arr1, arr2) # возведение элементов первого массива в степени второго массива
result

array([  1,  32, 729])

In [160]:
arr1 = np.array([np.nan, 2, 3])
arr2 = np.array([4, 5, 0])
result = np.fmax(arr1, arr2) # возвращает максимальные значения, игнорируя NaN
result

array([4., 5., 3.])

In [161]:
arr1 = np.array([np.nan, 2, 3])
arr2 = np.array([4, 5, 0])
result = np.fmin(arr1, arr2) # возвращает минимальные значения, игнорируя NaN
result

array([4., 2., 0.])

In [162]:
arr1 = np.array([45, 2, 3])
arr2 = np.array([4, 5, 2])
result = np.mod(arr1, arr2) # возвращает остатки от деления
result

array([1, 2, 1])

In [163]:
arr1 = np.array([45, -2, 3])
arr2 = np.array([-4, 5, -1])
result = np.copysign(arr1, arr2) # возвращает первое значение со знаком второго
result

array([-45.,   2.,  -3.])

In [164]:
arr1 = np.array([45, -2, 3])
arr2 = np.array([-4, 5, -1])
result = np.greater(arr1, arr2) # возвращает True, если первый элемент больше второго
result

array([ True, False,  True])

In [165]:
arr1 = np.array([45, -2, 3])
arr2 = np.array([-4, 5, -1])
result = np.greater_equal(arr1, arr2) # возвращает True, если первый элемент больше или равен второму
result

array([ True, False,  True])

In [166]:
arr1 = np.array([45, -2, 3])
arr2 = np.array([-4, 5, -1])
result = np.less(arr1, arr2) # возвращает True, если первый элемент меньше второго
result

array([False,  True, False])

In [167]:
arr1 = np.array([45, -2, 3])
arr2 = np.array([-4, 5, -1])
result = np.less_equal(arr1, arr2) # возвращает True, если первый элемент меньше или равен второму
result

array([False,  True, False])

In [168]:
arr1 = np.array([45, -2, 3])
arr2 = np.array([-4, 5, -1])
result = np.equal(arr1, arr2) # возвращает True, если элементы равны
result

array([False, False, False])

In [169]:
arr1 = np.array([45, -2, 3])
arr2 = np.array([-4, 5, -1])
result = np.not_equal(arr1, arr2) # возвращает True, если элементы НЕ равны
result

array([ True,  True,  True])

In [170]:
arr1 = np.array([True, False, True])
arr2 = np.array([True, True, False])
result = np.logical_and(arr1, arr2) # результат операции И (логического)
result     

array([ True, False, False])

In [171]:
arr1 = np.array([True, False, True])
arr2 = np.array([True, True, False])
result = np.logical_or(arr1, arr2) # результат операции ИЛИ (логического)
result     

array([ True,  True,  True])

In [172]:
arr1 = np.array([True, False, True])
arr2 = np.array([True, True, False])
result = np.logical_xor(arr1, arr2) # результат операции взаимоисключающего ИЛИ (логического)
result     

array([False,  True,  True])

**Задание 2:**

In [173]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

Статические методы массива: sum; mean; std, var; min, max; argmin, argmax; cumsum; cumprod.

**Задание 2:**

Привидите практические примеры всех статических методов массива, перечисленных выше. В отдельной строке перед
примером необходимо дать описание каждого метода

In [174]:
arr = np.array([1, 2, 3, 4, 5])
result = np.sum(arr) # сумма всех элемнтов
result

15

In [175]:
arr = np.array([1, 2, 3, 4, 5])
result = np.mean(arr) # среднее арифметическое массива
result

3.0

In [176]:
arr = np.array([1, 2, 3, 4, 5])
result = np.std(arr) # стандартное отклонение элементов массива
result

1.4142135623730951

In [177]:
arr = np.array([1, 2, 3, 4, 5])
result = np.var(arr) # вычисляет дисперсию
result

2.0

In [179]:
arr = np.array([1, 2, 3, 4, 5])
min_v = np.min(arr) # минимальное значение
max_v = np.max(arr) # максмимальное значение
print(min_v)
max_v

1


5

In [180]:
arr = np.array([1, 2, 3, 4, 5])
min_i = np.argmin(arr) # индекс минимального значения
max_i = np.argmax(arr) # индекс максмимального значения
print(min_i)
max_i

0


4

In [181]:
arr = np.array([1, 2, 3, 4, 5])
result = np.cumsum(arr) # каждый элемент - сумма предыдущих
result

array([ 1,  3,  6, 10, 15])

In [182]:
arr = np.array([1, 2, 3, 4, 5])
result = np.cumprod(arr) # каждый элемент - произведение предыдущих
result

array([  1,   2,   6,  24, 120])

**Методы булевых массивов:**

In [183]:
arr = np.random.randn(100)
(arr > 0).sum()

55

In [184]:
np.array([False, True]).any()

True

In [185]:
np.array([False, True]).all()

False

In [187]:
np.array([True, True]).all()

True

In [188]:
arr = np.random.randn(5)
arr

array([0.62220578, 0.22859009, 0.26204816, 1.07473848, 2.11184997])

In [190]:
arr.sort()
arr

array([0.22859009, 0.26204816, 0.62220578, 1.07473848, 2.11184997])

In [191]:
arr = np.random.randn(5, 3)
arr

array([[ 0.37446602, -1.49228448, -0.26416474],
       [ 0.13109971,  0.05213273, -0.26154269],
       [-1.41127733,  1.5568624 ,  0.06754481],
       [ 0.79194435,  1.91430282, -0.2772482 ],
       [-0.5498138 , -1.5610215 , -1.22290194]])

In [193]:
arr.sort(1)
arr

array([[-1.49228448, -0.26416474,  0.37446602],
       [-0.26154269,  0.05213273,  0.13109971],
       [-1.41127733,  0.06754481,  1.5568624 ],
       [-0.2772482 ,  0.79194435,  1.91430282],
       [-1.5610215 , -1.22290194, -0.5498138 ]])

In [195]:
arr = np.array(['Слово', 'Буква', 'Слово', 'Буква', 'Цифра', 'Число'])
np.unique(arr)

array(['Буква', 'Слово', 'Цифра', 'Число'], dtype='<U5')

**Задание 3:**

In [196]:
arr = np.array(['Слово', 'Буква', 'Слово', 'Буква', 'Цифра', 'Число'])
np.unique(arr) # возвращает отсортированный массив уникальных его значений 

array(['Буква', 'Слово', 'Цифра', 'Число'], dtype='<U5')

In [198]:
x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 5, 6])
result = np.intersect1d(x, y) # массив - пересечение массивов аргументов
result

array([3, 4])

In [200]:
x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 5, 6])
result = np.union1d(x, y) # объединение уникальных значений
result

array([1, 2, 3, 4, 5, 6])

In [201]:
x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 5, 6])
result = np.in1d(x, y) # проверка на наличие значений в массиве 
result

array([False, False,  True,  True])

In [202]:
x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 5, 6])
result = np.setdiff1d(x, y) # операция разности множеств 
result

array([1, 2])

In [203]:
x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 5, 6])
result = np.setxor1d(x, y) # операция симметрической разности множеств 
result

array([1, 2, 5, 6])

**Файловый ввод-вывод, линал, рандом**

In [204]:
arr = np.arange(4)
np.save('my_array_4_save', arr)

In [206]:
np.load('my_array_4_save.npy')

array([0, 1, 2, 3])

In [207]:
np.savez('array_archive.npz', a=arr, b=arr)

In [208]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3])

In [209]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [210]:
x = np.random.randn(2, 2)
y = np.random.randn(2)
x @ y

array([-0.3448094 , -0.78327044])

In [213]:
X = np.random.randn(5, 5)
mat = X.T.dot(X)
np.linalg.inv(mat)

array([[ 0.88609419, -0.10813999,  0.69978275, -0.85926274, -0.11417536],
       [-0.10813999,  4.71052528, -4.02391882,  9.66983062, -3.67411487],
       [ 0.69978275, -4.02391882,  4.3100424 , -9.34107426,  3.16977208],
       [-0.85926274,  9.66983062, -9.34107426, 22.1550018 , -8.03910187],
       [-0.11417536, -3.67411487,  3.16977208, -8.03910187,  3.33635853]])

In [215]:
q, r = np.linalg.qr(mat)
r

array([[-3.93692106,  1.19258182,  1.96577193, -1.2300888 , -3.80086156],
       [ 0.        , -2.68472087, -1.18629935, -0.24752879, -2.55572923],
       [ 0.        ,  0.        , -4.93536491, -3.50390692, -3.85761303],
       [ 0.        ,  0.        ,  0.        , -0.56374523, -1.53237419],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.10034272]])

In [224]:
np.random.seed(1234)

In [225]:
samples = np.random.normal(size=(4, 4))
samples

array([[ 4.71435164e-01, -1.19097569e+00,  1.43270697e+00,
        -3.12651896e-01],
       [-7.20588733e-01,  8.87162940e-01,  8.59588414e-01,
        -6.36523504e-01],
       [ 1.56963721e-02, -2.24268495e+00,  1.15003572e+00,
         9.91946022e-01],
       [ 9.53324128e-01, -2.02125482e+00, -3.34077366e-01,
         2.11836468e-03]])